a=input("Enter you name:")
b=input("Enter your profession[student/occupation]:")
c=input("Enter your field:")
d=input("Enter your [skills/tools]:")
e=input("Enter your [projects/interests]:")
f=input("Enter your process [studing/working on]:")
g=input("Enter your career goal:")
h=input("Enter your hobby[any one]:")
print("Hi, I'm",a,", a",b,"specializing in",c,". I have experience with",d,"and enjoy working on",e,". Currently, I am",f,"and aim to",g,". In my free time, I enjoy",h,".")